# Generated by Django 4.2.1 on 2023-05-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="handle",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
