# Generated by Django 4.2.1 on 2023-05-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_post_handle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="handle",
        ),
        migrations.AddField(
            model_name="user",
            name="handle",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
